# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x08\x63hatPack\"\x1b\n\x0b\x43hatRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\tChatReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"*\n\nStreamText\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\x87\x01\n\x0b\x43hatService\x12\x38\n\x08\x43hatFunc\x12\x15.chatPack.ChatRequest\x1a\x13.chatPack.ChatReply\"\x00\x12>\n\nChatStream\x12\x14.chatPack.StreamText\x1a\x14.chatPack.StreamText\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=27
  _globals['_CHATREQUEST']._serialized_end=54
  _globals['_CHATREPLY']._serialized_start=56
  _globals['_CHATREPLY']._serialized_end=83
  _globals['_STREAMTEXT']._serialized_start=85
  _globals['_STREAMTEXT']._serialized_end=127
  _globals['_CHATSERVICE']._serialized_start=130
  _globals['_CHATSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
