# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x08\x63hatPack\"\x1b\n\x0b\x43hatRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\tChatReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"*\n\nStreamText\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\x87\x01\n\x0b\x43hatService\x12\x38\n\x08\x43hatFunc\x12\x15.chatPack.ChatRequest\x1a\x13.chatPack.ChatReply\"\x00\x12>\n\nChatStream\x12\x14.chatPack.StreamText\x1a\x14.chatPack.StreamText\"\x00(\x01\x30\x01\x62\x06proto3')



_CHATREQUEST = DESCRIPTOR.message_types_by_name['ChatRequest']
_CHATREPLY = DESCRIPTOR.message_types_by_name['ChatReply']
_STREAMTEXT = DESCRIPTOR.message_types_by_name['StreamText']
ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatPack.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

ChatReply = _reflection.GeneratedProtocolMessageType('ChatReply', (_message.Message,), {
  'DESCRIPTOR' : _CHATREPLY,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatPack.ChatReply)
  })
_sym_db.RegisterMessage(ChatReply)

StreamText = _reflection.GeneratedProtocolMessageType('StreamText', (_message.Message,), {
  'DESCRIPTOR' : _STREAMTEXT,
  '__module__' : 'chatbot_pb2'
  # @@protoc_insertion_point(class_scope:chatPack.StreamText)
  })
_sym_db.RegisterMessage(StreamText)

_CHATSERVICE = DESCRIPTOR.services_by_name['ChatService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATREQUEST._serialized_start=27
  _CHATREQUEST._serialized_end=54
  _CHATREPLY._serialized_start=56
  _CHATREPLY._serialized_end=83
  _STREAMTEXT._serialized_start=85
  _STREAMTEXT._serialized_end=127
  _CHATSERVICE._serialized_start=130
  _CHATSERVICE._serialized_end=265
# @@protoc_insertion_point(module_scope)
